apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Values.namespaceOverride | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "8.0" }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"      # 어플 설정에 맞춰 root로 변경
            - name: MYSQL_DATABASE
              value: "kws"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
            - name: mysql-init-scripts
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-combined-config
            items:
              - key: my.cnf
                path: my.cnf
        - name: mysql-init-scripts
          configMap:
            name: mysql-combined-config
            items:
              - key: 01-init-root.sql  # ConfigMap의 01-init-root.sql 데이터를
                path: 01-init-root.sql # 컨테이너 내부 01-init-root.sql 파일로
              - key: 02-init-db.sql    # ConfigMap의 02-init-db.sql 데이터를
                path: 02-init-db.sql   # 컨테이너 내부 02-init-db.sql 파일로