version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks:
      - kwsbridge
    volumes:
      - kwsvol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root

volumes:
  kwsvol:

networks:
  kwsbridge: