apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "batch-server.fullname" . }}
  labels:
    {{- include "batch-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "batch-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "batch-server.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "batch-server.fullname" . }}
          env:
            - name: JAVA_OPTS
              value: "-Xms384m -Xmx512m -Dfile.encoding=UTF-8"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}